theme: jekyll-theme-minimal #jekyll-theme-minimal
title: [Hippolyte Mayard]
subtitle: [Hippolyte Mayard]
author: Hippolyte Mayard
description1: ğŸ‘¨ğŸ¼â€ğŸ’» Deep Learning engineer @Allisone.ai
description2: ğŸ‘¨ğŸ¼â€ğŸ“ MVA - ENS Paris-Saclay
description3: ğŸ‘¨ğŸ¼â€ğŸ“ IASD - UniversitÃ© Paris-Dauphine PSL


logo: /assets/images/image.png
simple_search: https://www.google.com/search
url_resume : https://drive.google.com/file/d/1RbZWu-W0E3sJWp1kgHFm0hGhP0rKqXTW/view?usp=sharing

header_navigation:
  - title: Home
    url: /index.md

show_downloads: false
google_analytics: false

github: 
  is_user_page: true
  is_project_page: false


markdown: kramdown
kramdown:
  math_engine: mathjax